/**
 * GENERATED by scripts/generateLevels.mjs — do not hand-edit.
 *
 * The three study levels. Every one is brute-forced before being written
 * here: each has exactly ONE valid colouring given its pre-coloured
 * regions, which is what stops the interchangeable-colours symmetry from
 * making "unique" meaningless. Re-check with `npm run verify-levels`.
 *
 * The rung is set by how tight the graph is relative to three colours, not
 * by how many regions it has. A full hexagon gives every interior region
 * six neighbours, so domains collapse at once and the whole map falls out
 * of forced moves alone — a bigger hexagon is a longer level, not a harder
 * one, and the most-constrained-first heuristic never gets used. Carving
 * bays into the map (L2) and leaving the map altogether (L3) drop the
 * degree, leave domains genuinely ambiguous, and are what make that
 * heuristic necessary rather than decorative.
 */

export interface ColourLevel {
  id: string;
  title: string;
  rule: string;
  note: string;
  kind: 'hex' | 'graph';
  k: number;
  nodes: { x: number; y: number; poly?: string }[];
  adj: number[][];
  given: Record<number, number>;
  solution: number[];
  view: { minX: number; minY: number; w: number; h: number };
  /** Measured, not guessed: how much of this level propagation can do alone. */
  stats: { regions: number; waves: number; forced: number; choices: number };
}
export const LEVELS: ColourLevel[] = [
  {
    "id": "l1",
    "title": "Level 1 · The rule",
    "rule": "Regions that touch can’t share a colour.",
    "note": "Every move here is forced. Colour whichever region has one colour left, and watch it decide the next one.",
    "kind": "hex",
    "k": 3,
    "nodes": [
      {
        "x": -72.74613391789285,
        "y": 0,
        "poly": "-36.4,-21.0 -36.4,21.0 -72.7,42.0 -109.1,21.0 -109.1,-21.0 -72.7,-42.0"
      },
      {
        "x": -36.373066958946424,
        "y": 63,
        "poly": "0.0,42.0 0.0,84.0 -36.4,105.0 -72.7,84.0 -72.7,42.0 -36.4,21.0"
      },
      {
        "x": -36.373066958946424,
        "y": -63,
        "poly": "0.0,-84.0 0.0,-42.0 -36.4,-21.0 -72.7,-42.0 -72.7,-84.0 -36.4,-105.0"
      },
      {
        "x": 0,
        "y": 0,
        "poly": "36.4,-21.0 36.4,21.0 0.0,42.0 -36.4,21.0 -36.4,-21.0 -0.0,-42.0"
      },
      {
        "x": 36.373066958946424,
        "y": 63,
        "poly": "72.7,42.0 72.7,84.0 36.4,105.0 0.0,84.0 0.0,42.0 36.4,21.0"
      },
      {
        "x": 36.373066958946424,
        "y": -63,
        "poly": "72.7,-84.0 72.7,-42.0 36.4,-21.0 0.0,-42.0 0.0,-84.0 36.4,-105.0"
      },
      {
        "x": 72.74613391789285,
        "y": 0,
        "poly": "109.1,-21.0 109.1,21.0 72.7,42.0 36.4,21.0 36.4,-21.0 72.7,-42.0"
      }
    ],
    "adj": [
      [
        3,
        2,
        1
      ],
      [
        4,
        3,
        0
      ],
      [
        5,
        0,
        3
      ],
      [
        6,
        5,
        2,
        0,
        1,
        4
      ],
      [
        6,
        3,
        1
      ],
      [
        2,
        3,
        6
      ],
      [
        5,
        3,
        4
      ]
    ],
    "given": {
      "0": 0,
      "3": 2
    },
    "solution": [
      0,
      1,
      1,
      2,
      0,
      0,
      1
    ],
    "view": {
      "minX": -114.7,
      "minY": -105,
      "w": 229.5,
      "h": 210
    },
    "stats": {
      "regions": 7,
      "waves": 3,
      "forced": 5,
      "choices": 0
    }
  },
  {
    "id": "l2",
    "title": "Level 2 · When nothing is forced",
    "rule": "Regions that touch can’t share a colour.",
    "note": "The forced moves run out partway. When they do, colour the region with the fewest colours left.",
    "kind": "hex",
    "k": 3,
    "nodes": [
      {
        "x": -145.4922678357857,
        "y": 0,
        "poly": "-109.1,-21.0 -109.1,21.0 -145.5,42.0 -181.9,21.0 -181.9,-21.0 -145.5,-42.0"
      },
      {
        "x": -109.11920087683927,
        "y": 63,
        "poly": "-72.7,42.0 -72.7,84.0 -109.1,105.0 -145.5,84.0 -145.5,42.0 -109.1,21.0"
      },
      {
        "x": -109.11920087683927,
        "y": -63,
        "poly": "-72.7,-84.0 -72.7,-42.0 -109.1,-21.0 -145.5,-42.0 -145.5,-84.0 -109.1,-105.0"
      },
      {
        "x": -72.74613391789285,
        "y": 0,
        "poly": "-36.4,-21.0 -36.4,21.0 -72.7,42.0 -109.1,21.0 -109.1,-21.0 -72.7,-42.0"
      },
      {
        "x": -36.373066958946424,
        "y": 63,
        "poly": "0.0,42.0 0.0,84.0 -36.4,105.0 -72.7,84.0 -72.7,42.0 -36.4,21.0"
      },
      {
        "x": 0,
        "y": 126,
        "poly": "36.4,105.0 36.4,147.0 0.0,168.0 -36.4,147.0 -36.4,105.0 -0.0,84.0"
      },
      {
        "x": -72.74613391789285,
        "y": -126,
        "poly": "-36.4,-147.0 -36.4,-105.0 -72.7,-84.0 -109.1,-105.0 -109.1,-147.0 -72.7,-168.0"
      },
      {
        "x": -36.373066958946424,
        "y": -63,
        "poly": "0.0,-84.0 0.0,-42.0 -36.4,-21.0 -72.7,-42.0 -72.7,-84.0 -36.4,-105.0"
      },
      {
        "x": 36.373066958946424,
        "y": 63,
        "poly": "72.7,42.0 72.7,84.0 36.4,105.0 0.0,84.0 0.0,42.0 36.4,21.0"
      },
      {
        "x": 72.74613391789285,
        "y": 126,
        "poly": "109.1,105.0 109.1,147.0 72.7,168.0 36.4,147.0 36.4,105.0 72.7,84.0"
      },
      {
        "x": 0,
        "y": -126,
        "poly": "36.4,-147.0 36.4,-105.0 0.0,-84.0 -36.4,-105.0 -36.4,-147.0 -0.0,-168.0"
      },
      {
        "x": 72.74613391789285,
        "y": 0,
        "poly": "109.1,-21.0 109.1,21.0 72.7,42.0 36.4,21.0 36.4,-21.0 72.7,-42.0"
      },
      {
        "x": 109.11920087683927,
        "y": 63,
        "poly": "145.5,42.0 145.5,84.0 109.1,105.0 72.7,84.0 72.7,42.0 109.1,21.0"
      },
      {
        "x": 72.74613391789285,
        "y": -126,
        "poly": "109.1,-147.0 109.1,-105.0 72.7,-84.0 36.4,-105.0 36.4,-147.0 72.7,-168.0"
      },
      {
        "x": 109.11920087683927,
        "y": -63,
        "poly": "145.5,-84.0 145.5,-42.0 109.1,-21.0 72.7,-42.0 72.7,-84.0 109.1,-105.0"
      },
      {
        "x": 145.4922678357857,
        "y": 0,
        "poly": "181.9,-21.0 181.9,21.0 145.5,42.0 109.1,21.0 109.1,-21.0 145.5,-42.0"
      }
    ],
    "adj": [
      [
        3,
        2,
        1
      ],
      [
        4,
        3,
        0
      ],
      [
        7,
        6,
        0,
        3
      ],
      [
        7,
        2,
        0,
        1,
        4
      ],
      [
        8,
        3,
        1,
        5
      ],
      [
        9,
        8,
        4
      ],
      [
        10,
        2,
        7
      ],
      [
        10,
        6,
        2,
        3
      ],
      [
        12,
        11,
        4,
        5,
        9
      ],
      [
        12,
        8,
        5
      ],
      [
        13,
        6,
        7
      ],
      [
        15,
        14,
        8,
        12
      ],
      [
        15,
        11,
        8,
        9
      ],
      [
        10,
        14
      ],
      [
        13,
        11,
        15
      ],
      [
        14,
        11,
        12
      ]
    ],
    "given": {
      "6": 2,
      "13": 0,
      "14": 1
    },
    "solution": [
      0,
      1,
      1,
      2,
      0,
      1,
      2,
      0,
      2,
      0,
      1,
      0,
      1,
      0,
      1,
      2
    ],
    "view": {
      "minX": -187.5,
      "minY": -168,
      "w": 375,
      "h": 336
    },
    "stats": {
      "regions": 16,
      "waves": 7,
      "forced": 7,
      "choices": 6
    }
  },
  {
    "id": "l3",
    "title": "Level 3 · No map at all",
    "rule": "Rivals can’t share a table.",
    "note": "Each colour is a table. Nothing here is decided for you.",
    "kind": "graph",
    "k": 3,
    "nodes": [
      {
        "x": 555.4,
        "y": 137.3
      },
      {
        "x": 178,
        "y": 236.9
      },
      {
        "x": 370.4,
        "y": 90
      },
      {
        "x": 143.9,
        "y": 72.6
      },
      {
        "x": 203.2,
        "y": 376.9
      },
      {
        "x": 82.6,
        "y": 429.6
      },
      {
        "x": 455.9,
        "y": 184.4
      },
      {
        "x": 389.6,
        "y": 302.9
      },
      {
        "x": 248.4,
        "y": 126.9
      },
      {
        "x": 315.8,
        "y": 202.7
      },
      {
        "x": 200.1,
        "y": 5.3
      },
      {
        "x": 363.5,
        "y": 18.2
      },
      {
        "x": 70.5,
        "y": 254.8
      },
      {
        "x": 264,
        "y": 294.4
      }
    ],
    "adj": [
      [
        6,
        7,
        11
      ],
      [
        4,
        7,
        10,
        12,
        13
      ],
      [
        6,
        10,
        11,
        13
      ],
      [
        9,
        10,
        11,
        12
      ],
      [
        1,
        5,
        7,
        9,
        12
      ],
      [
        4,
        12,
        13
      ],
      [
        0,
        2,
        7,
        8,
        9
      ],
      [
        0,
        1,
        4,
        6,
        9,
        13
      ],
      [
        6,
        10,
        11,
        12,
        13
      ],
      [
        3,
        4,
        6,
        7,
        11,
        13
      ],
      [
        1,
        2,
        3,
        8
      ],
      [
        0,
        2,
        3,
        8,
        9
      ],
      [
        1,
        3,
        4,
        5,
        8
      ],
      [
        1,
        2,
        5,
        7,
        8,
        9
      ]
    ],
    "given": {
      "0": 0,
      "10": 2
    },
    "solution": [
      0,
      0,
      0,
      1,
      1,
      0,
      1,
      2,
      0,
      0,
      2,
      2,
      2,
      1
    ],
    "view": {
      "minX": 36.5,
      "minY": -28.7,
      "w": 552.9,
      "h": 492.3
    },
    "stats": {
      "regions": 14,
      "waves": 0,
      "forced": 0,
      "choices": 12
    }
  }
];

export const COLOURS = ['#5ed3e8', '#ff9d5c', '#f79ad3'];
export const COLOUR_NAMES = ['Teal', 'Orange', 'Rose'];
