/**
 * GENERATED by scripts/generateLevels.mjs — do not hand-edit.
 *
 * The three study levels. Every one is brute-forced before being written
 * here: each has exactly ONE valid colouring given its pre-coloured
 * regions, which is what stops the interchangeable-colours symmetry from
 * making "unique" meaningless. Re-check with `npm run verify-levels`.
 *
 * The rung is set by how tight the graph is relative to three colours, not
 * by how many regions it has. A full hexagon gives every interior region
 * six neighbours, so domains collapse at once and the whole map falls out
 * of forced moves alone — a bigger hexagon is a longer level, not a harder
 * one, and the most-constrained-first heuristic never gets used. Carving
 * bays into the map (L2) and leaving the map altogether (L3) drop the
 * degree, leave domains genuinely ambiguous, and are what make that
 * heuristic necessary rather than decorative.
 */

export interface ColourLevel {
  id: string;
  title: string;
  rule: string;
  note: string;
  /** What this level calls its pieces and its choices, so no component hard-codes a story. */
  words: { thing: string; slot: string };
  /** Whether the pieces carry their own pictures. */
  icons: 'none' | 'animals';
  kind: 'hex' | 'graph';
  k: number;
  nodes: { x: number; y: number; poly?: string }[];
  adj: number[][];
  given: Record<number, number>;
  solution: number[];
  view: { minX: number; minY: number; w: number; h: number };
  /** Measured, not guessed: how much of this level propagation can do alone. */
  stats: { regions: number; waves: number; forced: number; choices: number };
}
export const LEVELS: ColourLevel[] = [
  {
    "id": "l1",
    "title": "Level 1 · One Rule",
    "rule": "Two regions that touch can’t be the same color.",
    "note": "Every move here decides itself. Find a region with one color left, fill it in, and watch what it does to the ones around it.",
    "words": {
      "thing": "region",
      "slot": "color"
    },
    "icons": "none",
    "kind": "hex",
    "k": 3,
    "nodes": [
      {
        "x": -72.74613391789285,
        "y": 0,
        "poly": "-36.4,-21.0 -36.4,21.0 -72.7,42.0 -109.1,21.0 -109.1,-21.0 -72.7,-42.0"
      },
      {
        "x": -36.373066958946424,
        "y": 63,
        "poly": "0.0,42.0 0.0,84.0 -36.4,105.0 -72.7,84.0 -72.7,42.0 -36.4,21.0"
      },
      {
        "x": -36.373066958946424,
        "y": -63,
        "poly": "0.0,-84.0 0.0,-42.0 -36.4,-21.0 -72.7,-42.0 -72.7,-84.0 -36.4,-105.0"
      },
      {
        "x": 0,
        "y": 0,
        "poly": "36.4,-21.0 36.4,21.0 0.0,42.0 -36.4,21.0 -36.4,-21.0 -0.0,-42.0"
      },
      {
        "x": 36.373066958946424,
        "y": 63,
        "poly": "72.7,42.0 72.7,84.0 36.4,105.0 0.0,84.0 0.0,42.0 36.4,21.0"
      },
      {
        "x": 36.373066958946424,
        "y": -63,
        "poly": "72.7,-84.0 72.7,-42.0 36.4,-21.0 0.0,-42.0 0.0,-84.0 36.4,-105.0"
      },
      {
        "x": 72.74613391789285,
        "y": 0,
        "poly": "109.1,-21.0 109.1,21.0 72.7,42.0 36.4,21.0 36.4,-21.0 72.7,-42.0"
      }
    ],
    "adj": [
      [
        3,
        2,
        1
      ],
      [
        4,
        3,
        0
      ],
      [
        5,
        0,
        3
      ],
      [
        6,
        5,
        2,
        0,
        1,
        4
      ],
      [
        6,
        3,
        1
      ],
      [
        2,
        3,
        6
      ],
      [
        5,
        3,
        4
      ]
    ],
    "given": {
      "0": 0,
      "3": 2
    },
    "solution": [
      0,
      1,
      1,
      2,
      0,
      0,
      1
    ],
    "view": {
      "minX": -114.7,
      "minY": -105,
      "w": 229.5,
      "h": 210
    },
    "stats": {
      "regions": 7,
      "waves": 3,
      "forced": 5,
      "choices": 0
    }
  },
  {
    "id": "l2",
    "title": "Level 2 · Your Call",
    "rule": "Two regions that touch can’t be the same color.",
    "note": "The free moves run out partway through. When they do, go for the region with the fewest colors left.",
    "words": {
      "thing": "region",
      "slot": "color"
    },
    "icons": "none",
    "kind": "hex",
    "k": 3,
    "nodes": [
      {
        "x": -145.4922678357857,
        "y": 0,
        "poly": "-109.1,-21.0 -109.1,21.0 -145.5,42.0 -181.9,21.0 -181.9,-21.0 -145.5,-42.0"
      },
      {
        "x": -109.11920087683927,
        "y": 63,
        "poly": "-72.7,42.0 -72.7,84.0 -109.1,105.0 -145.5,84.0 -145.5,42.0 -109.1,21.0"
      },
      {
        "x": -109.11920087683927,
        "y": -63,
        "poly": "-72.7,-84.0 -72.7,-42.0 -109.1,-21.0 -145.5,-42.0 -145.5,-84.0 -109.1,-105.0"
      },
      {
        "x": -72.74613391789285,
        "y": 0,
        "poly": "-36.4,-21.0 -36.4,21.0 -72.7,42.0 -109.1,21.0 -109.1,-21.0 -72.7,-42.0"
      },
      {
        "x": -36.373066958946424,
        "y": 63,
        "poly": "0.0,42.0 0.0,84.0 -36.4,105.0 -72.7,84.0 -72.7,42.0 -36.4,21.0"
      },
      {
        "x": 0,
        "y": 126,
        "poly": "36.4,105.0 36.4,147.0 0.0,168.0 -36.4,147.0 -36.4,105.0 -0.0,84.0"
      },
      {
        "x": -72.74613391789285,
        "y": -126,
        "poly": "-36.4,-147.0 -36.4,-105.0 -72.7,-84.0 -109.1,-105.0 -109.1,-147.0 -72.7,-168.0"
      },
      {
        "x": -36.373066958946424,
        "y": -63,
        "poly": "0.0,-84.0 0.0,-42.0 -36.4,-21.0 -72.7,-42.0 -72.7,-84.0 -36.4,-105.0"
      },
      {
        "x": 36.373066958946424,
        "y": 63,
        "poly": "72.7,42.0 72.7,84.0 36.4,105.0 0.0,84.0 0.0,42.0 36.4,21.0"
      },
      {
        "x": 72.74613391789285,
        "y": 126,
        "poly": "109.1,105.0 109.1,147.0 72.7,168.0 36.4,147.0 36.4,105.0 72.7,84.0"
      },
      {
        "x": 0,
        "y": -126,
        "poly": "36.4,-147.0 36.4,-105.0 0.0,-84.0 -36.4,-105.0 -36.4,-147.0 -0.0,-168.0"
      },
      {
        "x": 72.74613391789285,
        "y": 0,
        "poly": "109.1,-21.0 109.1,21.0 72.7,42.0 36.4,21.0 36.4,-21.0 72.7,-42.0"
      },
      {
        "x": 109.11920087683927,
        "y": 63,
        "poly": "145.5,42.0 145.5,84.0 109.1,105.0 72.7,84.0 72.7,42.0 109.1,21.0"
      },
      {
        "x": 72.74613391789285,
        "y": -126,
        "poly": "109.1,-147.0 109.1,-105.0 72.7,-84.0 36.4,-105.0 36.4,-147.0 72.7,-168.0"
      },
      {
        "x": 109.11920087683927,
        "y": -63,
        "poly": "145.5,-84.0 145.5,-42.0 109.1,-21.0 72.7,-42.0 72.7,-84.0 109.1,-105.0"
      },
      {
        "x": 145.4922678357857,
        "y": 0,
        "poly": "181.9,-21.0 181.9,21.0 145.5,42.0 109.1,21.0 109.1,-21.0 145.5,-42.0"
      }
    ],
    "adj": [
      [
        3,
        2,
        1
      ],
      [
        4,
        3,
        0
      ],
      [
        7,
        6,
        0,
        3
      ],
      [
        7,
        2,
        0,
        1,
        4
      ],
      [
        8,
        3,
        1,
        5
      ],
      [
        9,
        8,
        4
      ],
      [
        10,
        2,
        7
      ],
      [
        10,
        6,
        2,
        3
      ],
      [
        12,
        11,
        4,
        5,
        9
      ],
      [
        12,
        8,
        5
      ],
      [
        13,
        6,
        7
      ],
      [
        15,
        14,
        8,
        12
      ],
      [
        15,
        11,
        8,
        9
      ],
      [
        10,
        14
      ],
      [
        13,
        11,
        15
      ],
      [
        14,
        11,
        12
      ]
    ],
    "given": {
      "6": 2,
      "13": 0,
      "14": 1
    },
    "solution": [
      0,
      1,
      1,
      2,
      0,
      1,
      2,
      0,
      2,
      0,
      1,
      0,
      1,
      0,
      1,
      2
    ],
    "view": {
      "minX": -187.5,
      "minY": -168,
      "w": 375,
      "h": 336
    },
    "stats": {
      "regions": 16,
      "waves": 7,
      "forced": 7,
      "choices": 6
    }
  },
  {
    "id": "l3",
    "title": "Level 3 · The Zoo",
    "rule": "Animals that fight can’t share a zone.",
    "note": "Three zones, eleven animals, and nothing here is decided for you.",
    "words": {
      "thing": "animal",
      "slot": "zone"
    },
    "icons": "animals",
    "kind": "graph",
    "k": 3,
    "nodes": [
      {
        "x": 559.1,
        "y": 307.3
      },
      {
        "x": 455.9,
        "y": 113.9
      },
      {
        "x": 77.9,
        "y": 324.6
      },
      {
        "x": 775.4,
        "y": -115.2
      },
      {
        "x": -198.9,
        "y": 387.9
      },
      {
        "x": 148.6,
        "y": 445
      },
      {
        "x": -257.8,
        "y": 188.2
      },
      {
        "x": 679,
        "y": 101.2
      },
      {
        "x": 393.4,
        "y": -47.5
      },
      {
        "x": 165,
        "y": 186.4
      },
      {
        "x": 543.6,
        "y": 530.5
      }
    ],
    "adj": [
      [
        1,
        2,
        7,
        10
      ],
      [
        0,
        7,
        8,
        9
      ],
      [
        0,
        5,
        6
      ],
      [
        7,
        8
      ],
      [
        5,
        9
      ],
      [
        2,
        4,
        9,
        10
      ],
      [
        2,
        9
      ],
      [
        0,
        1,
        3,
        9
      ],
      [
        1,
        3,
        9
      ],
      [
        1,
        4,
        5,
        6,
        7,
        8
      ],
      [
        0,
        5
      ]
    ],
    "given": {
      "2": 1,
      "3": 0,
      "8": 2
    },
    "solution": [
      0,
      1,
      1,
      0,
      1,
      2,
      2,
      2,
      2,
      0,
      1
    ],
    "view": {
      "minX": -291.8,
      "minY": -149.2,
      "w": 1101.2,
      "h": 713.7
    },
    "stats": {
      "regions": 11,
      "waves": 0,
      "forced": 0,
      "choices": 8
    }
  }
];

export const COLOURS = ['#5ed3e8', '#ff9d5c', '#f79ad3'];
export const COLOUR_NAMES = ['Teal', 'Orange', 'Pink'];
